{% set name = "eozilla" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/eozilla-{{ version }}.tar.gz
  sha256: 6d6350f58fc8586697caadde2a7d3c728a63f76206414846171f7b7dbaa92257

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatch
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - appligator >=0.0.9
    - cuiman >=0.0.9
    - gavicore >=0.0.9
    - procodile >=0.0.9
    - wraptile >=0.0.9

test:
  imports:
    - eozilla
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/eo-tools/eozilla/tree/main/eozilla
  doc_url: https://eo-tools.github.io/eozilla/
  dev_url: https://github.com/eo-tools/eozilla/
  summary: Eozilla 🦖 has been developed to cloudify satellite data processor applications
  description: |
    Eozilla 🦖 is a suite of tools for workflow orchestration systems and a
    [OGC API - Processes](https://github.com/opengeospatial/ogcapi-processes)
    implementation.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AliceBalfanz
    - b-yogesh
    - clarasb
    - forman
    - konstntokas
    - pont-us
    - TejasMorbagal
    - thomasstorm
    - TonioF
